source 'https://rubygems.org'

gem 'rails', '4.2.6'
gem 'puma'

gem 'jwt_keeper', path: '..'

group :development, :test do
  gem 'dotenv-rails'

  gem 'pry'
  gem 'pry-stack_explorer'
  gem 'pry-rescue'
  gem 'pry-byebug'
end
