source 'https://rubygems.org'

gem 'puma'
gem 'rails', '~> 5.1.0'

gem 'jwt_keeper', path: '..'

group :development, :test do
  gem 'dotenv-rails'

  gem 'pry'
  gem 'pry-byebug'
  gem 'pry-rescue'
  gem 'pry-stack_explorer'
end
